#!/usr/bin/env python3
# Copyright 2024 Xarge AI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Verilog packaging tool — creates ZIP bundles or filelists from RTL sources.

Invoked by Bazel genrule targets generated by packaging/defs.bzl.
"""

import argparse
import os
import sys
import zipfile


def collect_files(src_args):
    """Flatten source arguments into a list of file paths."""
    files = []
    for src in src_args:
        for path in src:
            if os.path.isfile(path):
                files.append(path)
            elif os.path.isdir(path):
                for root, _, filenames in os.walk(path):
                    for fn in sorted(filenames):
                        files.append(os.path.join(root, fn))
    return files


def compute_arcname(filepath, prefix, strip_prefix, flatten):
    """Compute the archive name for a file."""
    if flatten:
        name = os.path.basename(filepath)
    else:
        name = filepath
        if strip_prefix and name.startswith(strip_prefix):
            name = name[len(strip_prefix):]
            name = name.lstrip("/")

    if prefix:
        name = os.path.join(prefix, name)

    return name


def create_zip(files, output, prefix, strip_prefix, flatten):
    """Create a ZIP archive from the given files."""
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        seen = set()
        for filepath in files:
            arcname = compute_arcname(filepath, prefix, strip_prefix, flatten)
            if arcname in seen:
                print(
                    f"WARNING: Duplicate entry '{arcname}' from '{filepath}', skipping",
                    file=sys.stderr,
                )
                continue
            seen.add(arcname)
            zf.write(filepath, arcname)

    print(f"Created ZIP: {output} ({len(seen)} files)")


def create_filelist(files, output, relative_to):
    """Create a .f filelist from the given files."""
    with open(output, "w") as f:
        for filepath in files:
            path = filepath
            if relative_to and path.startswith(relative_to):
                path = path[len(relative_to):]
                path = path.lstrip("/")
            f.write(path + "\n")

    print(f"Created filelist: {output} ({len(files)} files)")


def main():
    parser = argparse.ArgumentParser(description="Verilog Packaging Tool")
    parser.add_argument("--output", required=True, help="Output file path")
    parser.add_argument(
        "--mode",
        required=True,
        choices=["zip", "filelist"],
        help="Output mode",
    )
    parser.add_argument(
        "--src",
        action="append",
        nargs="+",
        default=[],
        help="Source files to include",
    )
    parser.add_argument("--prefix", default="", help="Prefix inside ZIP")
    parser.add_argument(
        "--strip-prefix", default="", help="Strip this prefix from paths"
    )
    parser.add_argument(
        "--flatten", action="store_true", help="Flatten directory structure"
    )
    parser.add_argument(
        "--relative-to",
        default="",
        help="Make filelist paths relative to this dir",
    )

    args = parser.parse_args()

    # Flatten --src (nargs="+" gives list of lists)
    flat_srcs = []
    for group in args.src:
        flat_srcs.extend(group)
    args.src = flat_srcs

    files = collect_files([args.src])

    if not files:
        print("WARNING: No files to package", file=sys.stderr)

    if args.mode == "zip":
        create_zip(files, args.output, args.prefix, args.strip_prefix, args.flatten)
    elif args.mode == "filelist":
        create_filelist(files, args.output, args.relative_to)


if __name__ == "__main__":
    main()
