#!/usr/bin/env python3
# Copyright 2024 Xarge AI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
RTL lint runner supporting Verilator, Verible, and commercial tools.

Invoked by Bazel py_test targets generated by lint/defs.bzl.
"""

import argparse
import os
import shutil
import subprocess
import sys


def find_tool(name):
    """Find a tool on PATH, returning its absolute path or None."""
    return shutil.which(name)


def run_verilator_lint(args):
    """Run verilator --lint-only."""
    verilator = find_tool("verilator")
    if not verilator:
        print("SKIP: verilator not found on PATH", file=sys.stderr)
        sys.exit(0)

    cmd = [verilator, "--lint-only"]

    if args.top:
        cmd.extend(["--top-module", args.top])
    else:
        # Infer top module from first source filename
        if args.src:
            basename = os.path.basename(args.src[0])
            stem = os.path.splitext(basename)[0]
            cmd.extend(["--top-module", stem])

    # Default: enable all warnings
    cmd.append("-Wall")

    for d in args.define:
        cmd.extend(["+define+" + d])

    if args.waiver:
        cmd.extend([args.waiver])

    for f in args.flag:
        cmd.append(f)

    # Add source files (resolve to absolute paths)
    for src in args.src:
        cmd.append(os.path.abspath(src))

    print(f"Running: {' '.join(cmd)}", file=sys.stderr)
    result = subprocess.run(cmd, capture_output=True, text=True)

    # Print stdout/stderr
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        # Verilator prints report lines to stderr; filter for warnings/errors
        lines = result.stderr.strip().split("\n")
        warnings = []
        for line in lines:
            if "%Warning" in line or "%Error" in line:
                warnings.append(line)
            elif line.startswith("- V e r i l") or line.startswith("- Verilator"):
                pass  # Skip report header
            else:
                warnings.append(line)
        if warnings:
            lint_output = "\n".join(warnings)
            print(lint_output)

    if result.returncode != 0:
        print(f"\nVerilator lint FAILED (exit code {result.returncode})")
        sys.exit(1)
    else:
        print("Verilator lint PASSED")


def run_verible_lint(args):
    """Run verible-verilog-lint."""
    verible = find_tool("verible-verilog-lint")
    if not verible:
        print("SKIP: verible-verilog-lint not found on PATH", file=sys.stderr)
        sys.exit(0)

    cmd = [verible]

    if args.rules_config:
        cmd.extend(["--rules_config", os.path.abspath(args.rules_config)])

    if args.waiver:
        cmd.extend(["--waiver_files", os.path.abspath(args.waiver)])

    # Build rules string from --rule-on / --rule-off
    rules_parts = []
    for r in args.rule_on:
        rules_parts.append(r)
    for r in args.rule_off:
        rules_parts.append("-" + r)
    if rules_parts:
        cmd.extend(["--rules", ",".join(rules_parts)])

    # Add source files
    for src in args.src:
        cmd.append(os.path.abspath(src))

    print(f"Running: {' '.join(cmd)}", file=sys.stderr)
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr)

    if result.returncode != 0:
        print(f"\nVerible lint FAILED (exit code {result.returncode})")
        sys.exit(1)
    else:
        print("Verible lint PASSED")


def run_commercial_lint(args):
    """Run commercial lint tool (SpyGlass, VCStatic, Ascent)."""
    tool_map = {
        "spyglass": {
            "binary": "sg_shell",
            "env_var": "SPYGLASS_HOME",
        },
        "vcstatic": {
            "binary": "vc_static_shell",
            "env_var": "VC_STATIC_HOME",
        },
        "ascent": {
            "binary": "ascentlint",
            "env_var": "ASCENT_HOME",
        },
    }

    tool_info = tool_map.get(args.tool)
    if not tool_info:
        print(f"ERROR: Unknown commercial lint tool: {args.tool}", file=sys.stderr)
        print(f"Supported: {', '.join(tool_map.keys())}", file=sys.stderr)
        sys.exit(1)

    binary = find_tool(tool_info["binary"])
    if not binary:
        env_home = os.environ.get(tool_info["env_var"], "")
        if env_home:
            candidate = os.path.join(env_home, "bin", tool_info["binary"])
            if os.path.isfile(candidate):
                binary = candidate

    if not binary:
        print(
            f"SKIP: {tool_info['binary']} not found on PATH "
            f"(set {tool_info['env_var']} or add to PATH)",
            file=sys.stderr,
        )
        sys.exit(0)

    # Generate filelist
    tmpdir = os.environ.get("TEST_TMPDIR", "/tmp")
    filelist = os.path.join(tmpdir, "lint_sources.f")
    with open(filelist, "w") as f:
        for d in args.define:
            f.write(f"+define+{d}\n")
        for src in args.src:
            f.write(os.path.abspath(src) + "\n")

    if args.tool == "spyglass":
        # SpyGlass TCL-based flow
        tcl_file = os.path.join(tmpdir, "spyglass_lint.tcl")
        with open(tcl_file, "w") as f:
            f.write(f"new_project spyglass_lint -force\n")
            f.write(f"read_file -type sourcelist {filelist}\n")
            if args.top:
                f.write(f"set_option top {args.top}\n")
            if args.waiver:
                f.write(f"read_file -type waiver {os.path.abspath(args.waiver)}\n")
            f.write("current_goal lint/lint_rtl\n")
            f.write("run_goal\n")
            report = os.path.join(tmpdir, "spyglass_report.rpt")
            f.write(f"write_report moresimple > {report}\n")
            f.write("exit -force\n")
        cmd = [binary, "-tcl", tcl_file]

    elif args.tool == "vcstatic":
        # VCStatic project file flow
        prj_file = os.path.join(tmpdir, "vcstatic_lint.tcl")
        with open(prj_file, "w") as f:
            f.write(f"read_file -type sourcelist {filelist}\n")
            if args.top:
                f.write(f"set_option top {args.top}\n")
            if args.waiver:
                f.write(f"read_file -type waiver {os.path.abspath(args.waiver)}\n")
            f.write("current_goal lint/lint_rtl_check\n")
            f.write("run_goal\n")
            report = os.path.join(tmpdir, "vcstatic_report.rpt")
            f.write(f"report_result -force {report}\n")
            f.write("exit\n")
        cmd = [binary, "-file", prj_file]

    elif args.tool == "ascent":
        cmd = [binary]
        if args.top:
            cmd.extend(["-top", args.top])
        cmd.extend(["-f", filelist])
        if args.waiver:
            cmd.extend(["-waiver", os.path.abspath(args.waiver)])
        for f_flag in args.flag:
            cmd.append(f_flag)

    print(f"Running: {' '.join(cmd)}", file=sys.stderr)
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr)

    if result.returncode != 0:
        print(f"\n{args.tool} lint FAILED (exit code {result.returncode})")
        sys.exit(1)
    else:
        print(f"{args.tool} lint PASSED")


def main():
    parser = argparse.ArgumentParser(description="RTL Lint Runner")
    parser.add_argument("--tool", required=True,
                        choices=["verilator", "verible", "spyglass", "vcstatic", "ascent"],
                        help="Lint tool to use")
    parser.add_argument("--src", action="append", nargs="+", default=[],
                        help="Source files to lint")
    parser.add_argument("--top", default=None,
                        help="Top module name")
    parser.add_argument("--define", action="append", default=[],
                        help="Preprocessor defines")
    parser.add_argument("--flag", action="append", default=[],
                        help="Extra tool-specific flags")
    parser.add_argument("--waiver", default=None,
                        help="Waiver/config file")
    parser.add_argument("--rules-config", default=None,
                        help="Rules configuration file (Verible)")
    parser.add_argument("--rule-on", action="append", default=[],
                        help="Enable specific rule (Verible)")
    parser.add_argument("--rule-off", action="append", default=[],
                        help="Disable specific rule (Verible)")

    args = parser.parse_args()

    # Flatten --src (nargs="+" gives list of lists)
    flat_srcs = []
    for group in args.src:
        flat_srcs.extend(group)
    args.src = flat_srcs

    if not args.src:
        print("ERROR: No source files specified", file=sys.stderr)
        sys.exit(1)

    if args.tool == "verilator":
        run_verilator_lint(args)
    elif args.tool == "verible":
        run_verible_lint(args)
    else:
        run_commercial_lint(args)


if __name__ == "__main__":
    main()
